name: freezed_provider_value_notifier
description: A new Flutter project.

version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ^3.9.0

dependencies:
  collection:
  flutter:
    sdk: flutter
  freezed_annotation:
  provider:
  todos_app_core:
    path: ../todos_app_core
  todos_repository_core:
    path: ../todos_repository_core
  todos_repository_local_storage:
    path: ../todos_repository_local_storage
  shared_preferences:

dev_dependencies:
  build_runner:
  integration_tests:
    path: ../integration_tests
  integration_test:
    sdk: flutter
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed:
  mockito:
  test:

flutter:
  uses-material-design: true
