name: integration_tests
description: An integration test suite for the Flutter Architecture Samples

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  test:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
