name: simple_blocs
description: The Business Logic Components for a Todo App - Simplfied
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.9.0

dependencies:
  collection: ^1.15.0
  meta: ^1.15.0
  rxdart: ^0.28.0
  todos_repository_core:
    path: ../todos_repository_core

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  mockito: ^5.5.0
