name: Static Analysis & Tests

on:
  pull_request:
  push:
    branches:
      - main
      - refresh

jobs:
  todos_repository_local_storage:
    name: Todos Repository Local Storage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Static Analysis & Tests
        uses: ./.github/actions/flutter_analysis_and_tests
        with:
          working-directory: ./todos_repository_local_storage
          run-integration-tests: false
  vanilla:
    name: Vanilla
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Static Analysis & Tests
        uses: ./.github/actions/flutter_analysis_and_tests
        with:
          working-directory: ./vanilla
  inherited_widget:
    name: Inherited Widget
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Static Analysis & Tests
        uses: ./.github/actions/flutter_analysis_and_tests
        with:
          working-directory: ./inherited_widget
  read_coverage:
    name: Read Combined Coverage Files
    runs-on: ubuntu-latest
    needs: [todos_repository_local_storage, vanilla, inherited_widget]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: List coverage files
        run: ls -l coverage-lcov-*.info || echo "No coverage files found"
      - name: Show coverage files content
        run: |
          for f in coverage-lcov-*.info; do
            echo "\n==== $f ===="
            cat "$f"
          done || echo "No coverage files to show"
