name: Validation

on:
  pull_request:
  push:
    branches:
      - main
      - refresh

jobs:
  vanilla:
    name: Vanilla
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vanilla
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/app_validation
